### ISSUE TITLE
RTSP is not working for HD (1280x720)resolution

### ISSUE THREAD

**Issue by Bhavyashri** [ant-thomas/zsgx1hacks#136]
I have implemented RTSP sever camera for different resolution like QVGA,VGA and HD.its working fine upto VGA resolution from capturing to display in VLC. after that it is not playing for HD res,I have checked the data(image) in DDR(it is capturing) and RGB buffer (image compression) here also it is showing the image but it is not coming to the display in VLC?Can anyone suggest me to overcome from this problem? 
Thank you.

**Comment by InFaMouS9t85** [comment]
rtsp://admin@Cam-IP:8001/0/av0 (for high resolution)
rtsp://admin@CamIP:8001/0/av1 (for low resolution)

**Comment by Bhavyashri** [comment]
Thank you
