### ISSUE TITLE
Remove rtsp authentication

### ISSUE THREAD

**Issue by kotfarepra** [ant-thomas/zsgx1hacks#16]
hello 
Trying to set up a server with ffmpeg to convert the RTSP of the camera to hls . 
Ffmpeg doesnt like how the authentication is setup on the RTSP server of camera.

Is there a way to make the rtsp server accessible without user/pass ?

meaning rtsp://192.168.1.15:554 instead of rtsp://admin:admin@192.168.1.15:554 ?

Thanks

**Comment by nestoroa** [comment]
Hi, I take screenshots from the RTSP with this shell script:
`ffmpeg -i "rtsp://admin:admin@192.168.0.241:554" -y -f image2  -frames 1 /home/USER/snapshot.jpeg`
Maybe it will help you.

**Comment by kotfarepra** [comment]
I tried that too but still get the same error 

Using admin/admin
[rtsp @ 0x16e0570] method DESCRIBE failed: 401 Unauthorized
rtsp://admin:admin@192.168.1.115:554: Server returned 401 Unauthorized (authorization failed)


Using just username admin and blank password
[rtsp @ 0x16e0570] method DESCRIBE failed: 401 Unauthorized
rtsp://admin@192.168.1.115:554: Server returned 401 Unauthorized (authorization failed)

**Comment by kotfarepra** [comment]
Even tried with ffprobe and still same problem

ffprobe rtsp://admin@192.168.1.15:554

**Comment by nestoroa** [comment]
try rtsp://admin:@192.168.1.15:554

**Comment by nestoroa** [comment]
Also share here your firmware version

**Comment by kotfarepra** [comment]
That last command did it :)

Thanks

**Comment by ant-thomas** [comment]
Glad to see you've sorted it. On a camera that hasn't been configured by the app there is no password, just a username of ```admin```

**Comment by kotfarepra** [comment]
Yeah , i did the configuration via the app and was just playing with the options ( telnet ) that are available without flashing the camera with the "hack" file on this github repo. 

Thought since the others ( vlc , live555 ) were connecting OK , then even FFMPEG would be ok .... but hey you learn something new everyday :)

Thanks once again

**Comment by kotfarepra** [comment]
By the way , referring to  what you said above 

i did the configuration via the app and it was still without password ( just username admin ) for RTSP 

My camera is "GUUDGO GD-SC02" and the infos from the APP are as below 

model type : 
eyeplus_ipc_gk_002

Firmware : 
3.1.1.0908

Embedded Application
3.1.1.0908
