### ISSUE TITLE
domainlist in p2pcam

### ISSUE THREAD

**Issue by Itsme7** [ant-thomas/zsgx1hacks#18]
I opened the p2pcam file in a text editor an found a list of domains. Don't know if these are all used. Most of these domains are in the new hosts file her but there are also some additional domains.

xmpp.stg.closeli.com 
relayus-w.stg.arcsoftcloud.com 
update.stg.closeli.com 
esd.stg.closeli.com 
upns.stg.arcsoftcloud.com 
argus.stg.closeli.com 
argus.closeli.com 
relay.stg.closeli.com 
api.stg.closeli.com 
xmpp.icloseli.com 
relayus-w.arcsoftcloud.com 
update.icloseli.com 
esd.icloseli.com 
upns.icloseli.com 
argus.icloseli.com 
relay.icloseli.com 
api.icloseli.com 
xmpp.stg.icloseli.cn 
relaycn.arcsoftcloud.com 
update.stg.icloseli.cn 
esd.stg.icloseli.cn 
upns.stg.icloseli.cn 
argus.stg.icloseli.cn 
relay.stg.icloseli.cn 
stun.closeli.cn 
api.stg.icloseli.cn 
bell.stg.closeli.cn 
xmpp.icloseli.cn 
update.icloseli.cn 
esd.icloseli.cn 
upns.icloseli.cn 
argus.icloseli.cn 
relay.icloseli.cn 
stun.icloseli.cn 
api.icloseli.cn 
bell.closeli.cn

**Comment by ant-thomas** [comment]
Thanks for that.
I've updated the hosts file with the extra domains.
