### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by Kev0123** [ant-thomas/zsgx1hacks#2]
Hi there,

great to see this hack happen.
I'm not really in it so could you please give some idiot proof advise how to flash this version?
I would like to kill the connection to china at least.

Regards 
Kev0

**Comment by ant-thomas** [comment]
If you have already setup the camera via the app, download the files in the "sdcard" folder to a micro SD card formatted to vfat/fat32, insert that micro SD card into the camera and let it boot.

If it works the app won't connect to the camera, but you will still have an RTSP server on the IP address of the camera.

**Comment by ant-thomas** [comment]
Basic instructions added to Readme
