### ISSUE TITLE
Help my camera! :)

### ISSUE THREAD

**Issue by kkm0614** [ant-thomas/zsgx1hacks#6]
Hey guys!

I ordered a Gearbest camera: ZS - GX1 1080P WiFi IP Camera Webcam.
This can only be used with eyepluspilot.com or by phone. I would like to use it as described, but I do not have the knowledge to install it. Please make a "how-made" video for users, which everyone uses for their own responsibility. I tried Telnet, but I do not know the password.
Features:
Camera Version
Firmware: 3.1.1.0908
Embedded Application: 3.1.1.0908
Device ID: ******************
MAC Address: ******
Model Type: CloudCamera
Anti Flicker: 60Hz

I'm sorry about English, I'm writing about Hungary.

All my respect, Mark!

**Comment by kkm0614** [comment]
Hello!

It works : rtsp://admin:admin@<camera_ip_address>:8001/onvif1

**Comment by kotfarepra** [comment]
What firmware version  is your camera?

**Comment by kkm0614** [comment]
ZS - GX1 1080P
Firmware: 3.1.1.0908

**Comment by kotfarepra** [comment]
Can you confirm it works without internet from your modem?

**Comment by kkm0614** [comment]
Network can be used without the use of the internet. (No internet=Network it works) :D

**Comment by kkm0614** [comment]
the ispy program can not use the camera. it would be nice if PTZ were to go too.

**Comment by kotfarepra** [comment]
Great, dont update the firmware. I heard that the new version doesn't has
access

Regards

**Comment by sanscorp1** [comment]
Rtsp / onvif 1.2 are enabled by default on the mentioned firmware. Onvif device manager (sourceforge) can access the livestream and ptz.

Today I recieved a usb to ttl interface, I'm going to rip the filesystem from a tenvis camera with embedded web interface.

I also replied under the initial readme here, but didn't know if it was the right place. I have no experience with hacking or linux, just trying stuff.

**Comment by kkm0614** [comment]
Ispy opensource program work. The ptz option is still in question.

**Comment by ant-thomas** [comment]
I can confirm that PTZ does work via onvif!

I tried it using the tinyCam Free app on Android

**Comment by ant-thomas** [comment]
Updated instructions
