### ISSUE TITLE
I have not acces to WEBUI, SSH, FTP

### ISSUE THREAD

**Issue by CRACKISH** [ant-thomas/zsgx1hacks#75]
I have not acces toWebUI.

I go to http://192.168.0.101:8080/cgi-bin/webui but nothing((
When i go just to http://192.168.0.101/ i redirected to http://192.168.0.101/index.asp and nothing((

How can i enable ssh? telnet is work fine.

And what you mean about ftp? It's create ftp server on camera?

Camera: GD-SC03
Firmware 3.2.8.03.08

**Comment by ant-thomas** [comment]
Check out the new read-only hack and report back

**Comment by CRACKISH** [comment]
Yes, it's works)) thanks

**Comment by xlucasfelix** [comment]
@ant-thomas are you alive!!! hahaha when will we get an update?

**Comment by ant-thomas** [comment]
@xlucasfelix An update for what?

**Comment by xlucasfelix** [comment]
@ant-thomas Performance improvements (fps), adding new features requested here in github
(sd card recording, disable blue led, more robust interface and etc ...) :/

**Comment by ant-thomas** [comment]
You do realise that this is a small hack to mainly stop the cameras talking to the cloud?
If you want a camera which produces a better quality picture with all those features you'll likely need to buy a better more expensive camera.
