### ISSUE TITLE
Support for GC15H

### ISSUE THREAD

**Issue by theNailz** [ant-thomas/zsgx1hacks#76]
I've got a [GC15H](https://aliexpress.com/item/KERUI-1080P-Full-HD-Indoor-Wireless-Home-Security-WiFi-Cloud-Storage-IP-Camera-Surveillance-Camera-Home/32849963845.html) camera that's not supported by v0.4. Is there a way I could troubleshoot or debug the hack? 

What's the (supposed) entrypoint of the hack; is that `/mnt/debug_cmd.sh`? Should I dump the filesystem for starters?

**Comment by theNailz** [comment]
Alright, the GC15H has a read only filesystem that can't be mounted rw; by running all tools from the sdcard I managed to start the webserver (PTZ works, IR doesn't) and dropbear ssh server. Haven't tested the rest of the tools.
I'll see if I can finish the script RO-style and check the rest if the tools will work as well.

**Comment by ant-thomas** [comment]
I've just received the exact same camera and I'm working on making some mods on it.

**Comment by theNailz** [comment]
@ant-thomas Are you on Discord? I'd like to share some ideas

**Comment by ant-thomas** [comment]
@theNailz I think so (ant#7477)

**Comment by theNailz** [comment]
Is now supported 0348815374ce74e800521e7c1d75d112ceba284c
