### ISSUE TITLE
ftp on DG-Wo1f

### ISSUE THREAD

**Issue by gecko749** [ant-thomas/zsgx1hacks#82]
I tried the readonly-hack on my cam with latest Firmware.

Tests were ok but the ftp didn't work.

After some resaerch I found a hint and changed the command
`# start ftp server`
`/home/busybox/tcpsvd -E 0.0.0.0 21 /home/busybox/ftpd -w /media &`

Now it is working.

regards 

gecko

**Comment by ant-thomas** [comment]
Thanks.
Updated to fix.
