### ISSUE TITLE
RTSP does not seem to be running

### ISSUE THREAD

**Issue by techspy2000** [ant-thomas/zsgx1hacks#98]
I have successfully used the RO hack on this camera;

https://www.banggood.com/1080P-Outdoor-Wireless-WIFI-IR-Security-IP-Camera-Night-Vision-Intelligent-HD-Surveillance-Camera-p-1407809.html?utm_design=41&utm_source=emarsys&utm_medium=Shipoutinform171129&utm_campaign=trigger-emarsys&utm_content=Winna&sc_src=email_2671705&sc_eh=384351fb6a4544241&sc_llid=9887775&sc_lid=104858042&sc_uid=RNUAQjbElw&cur_warehouse=CN

I can access the webui page, telnet etc but I have not been able to find a video stream. I have tried VLC and ONVIF Device Manager (it doesn't detect the device/IP) NMAP shows the following;

PORT     STATE SERVICE
21/tcp   open  ftp
22/tcp   open  ssh
23/tcp   open  telnet
843/tcp  open  unknown
5050/tcp open  mmcc
7103/tcp open  unknown
8001/tcp open  vcom-tunnel
8080/tcp open  http-proxy

Any ideas how I can access the video stream?

Thanks

**Comment by paus56** [comment]
отсутствие потока RTSP на 554 порту и отсутствие ONVIF в камере возможно при отсутствии записи:
support_onvif = 1
в файле hwcfg.ini

Google translate:
the absence of the RTSP stream on port 554 and the absence of ONVIF in the camera is possible if there is no recording:
support_onvif = 1
in the hwcfg.ini file
